### ISSUE TITLE
Clustering_PushpinList - not clickable after zooming in

### ISSUE THREAD

**Issue by vinothbabu** [Microsoft/BingMapsV8CodeSamples#2]
While grouping a list of pins, the pins become not clickable once its zoomed in, also the position of the infobox is not visible inside the map for pins in the corner. 

> https://github.com/Microsoft/BingMapsV8CodeSamples/blob/master/Samples/Clustering/Clustering_PushpinList.html

Is this the desired behaviour?

**Comment by rbrundritt** [comment]
This is a bug in the Bing Maps API, not the sample. This has been discussed in a number of threads on the Bing Maps forums: https://social.msdn.microsoft.com/Forums/en-US/home?category=bingmaps
This issue is resolved in the experimental branch of Bing Maps. The main release branch will be updated in a couple of weeks after the Microsoft Build conference.
