### ISSUE TITLE
Possible XSS using InfoboxOptions.description field

### ISSUE THREAD

**Issue by jekel1818** [Microsoft/BingMapsV8CodeSamples#29]
I am not sure if this is a feature or a bug, but it is possible to inject executable javascript in the Map component using the `description` field of the `InfoboxOptions` object.

The doc doesn't give the impression that arbitrary javascript can be used here:
![Screen Shot 2020-09-29 at 9 20 11 PM](https://user-images.githubusercontent.com/8727739/94632937-e2028580-0299-11eb-8479-b4d8ae554db4.png)

However, the `description` string is not escape, resulting in possible javascript execution:

```
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />

    <!-- Reference to the Bing Maps SDK -->
    <script type='text/javascript'
            src='http://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=[key]' 
            async defer></script>
    
    <script type='text/javascript'>
    function GetMap()
    {
        var map = new Microsoft.Maps.Map('#myMap');

        var center = map.getCenter();

        var infobox = new Microsoft.Maps.Infobox(center, {
            title: 'Map Center',
            description: `Seattle<img src="" onerror="alert(1);console.log(2)"/>`
        });

        //Assign the infobox to a map instance.
        infobox.setMap(map);

        //Add your post map load code here.
    }
    </script>
</head>
<body>
    <div id="myMap" style="position:relative;width:600px;height:400px;"></div>
</body>
</html>
```

**Comment by IoTGirl** [comment]
Hello @jekel1818,

My apologies for the late response! We don’t escape the description because a user of the hosting page has no way of setting the infobox properties and injecting any code. We normally only escape input fields or any ways that a user can inject text. In this case **only the developer of the page** using map and adding the infobox has control over the infobox contents.

Sincerely,
IoTGirl
